apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: etcd
  labels:
    k8s-app: etcd
spec:
  selector:
    k8s-app: etcd
  type: ClusterIP
  clusterIP: None
  ports:
  - name: port
    port: 2379
    targetPort: 2379
    protocol: TCP
